# Generated by Django 6.0.3 on 2026-03-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_directmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, choices=[('CTU', 'CTU - Cebu Technological University'), ('CEC', 'CEC - Cebu Eastern College'), ('SWU', 'SWU - Southwestern University'), ('ACT', 'ACT - Asian College of Technology'), ('UV', 'UV - University of the Visayas')], default='', max_length=10),
        ),
    ]
