# Generated by Django 6.0.3 on 2026-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
