# Generated by Django 6.0.3 on 2026-03-31 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_postcomment_is_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('todo', 'To-Do List'), ('project', 'Project Tracker'), ('brainstorm', 'Brainstorm'), ('goal', 'Goal Tracker'), ('note', 'Notes')], max_length=20)),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('color', models.CharField(default='#4E7C3F', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#fef9c3', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.workspacedoc')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
