# Generated by Django 6.0.3 on 2026-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workspacedoc_workspaceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspaceitem',
            name='effort',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], default='m', max_length=5),
        ),
        migrations.AddField(
            model_name='workspaceitem',
            name='task_type',
            field=models.CharField(blank=True, choices=[('feature', 'Feature'), ('bug', 'Bug'), ('research', 'Research'), ('meeting', 'Meeting'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
