# Generated by Django 6.0.3 on 2026-03-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_workspaceitem_description_workspaceitem_effort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceitem',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspaceitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacedoc',
            name='type',
            field=models.CharField(choices=[('todo', 'To-Do List'), ('project', 'Project Tracker'), ('goal', 'Goal Tracker'), ('note', 'Notes')], max_length=20),
        ),
    ]
